SELECT a.FUNDING_OFFICE_NUM   AS "FUNDING OFFICE NUMBER"
      ,fo.FUNDING_OFFICE_ABBR AS "FUNDING OFFICE ABBREVIATION"
      ,fo.FUNDING_OFFICE_DESC AS "FUNDING OFFICE NAME"
      ,a.AAPP_NUM             AS "AAPP NUMBER"
      ,NVL(to_char(a.CENTER_ID),'Center ID is not avalable') AS "CENTER ID"
      ,NVL(c.CENTER_CODE,'Center Code is not available')     AS "CENTER CODE"
      ,NVL(c.CENTER_NAME,'Center Name is not available')     AS "CENTER NAME"
      ,NVL(to_char(a.CONTRACTOR_ID),'Contractor ID is not available') AS "CONTRACTOR ID"
      ,NVL(cr.CONTRACTOR_NAME,'Contractor Name is not available')     AS "CONTRACTOR NAME"
      ,a.CONTRACT_NUM AS "CONTRACT NUMBER"
      ,TO_CHAR (contract.fun_getaappdate (a.AAPP_NUM, CONTRACT.FUN_GETCURRNTCONTRACT_YEAR(a.AAPP_NUM), 'S'),'mm/dd/yyyy') AS "START DATE"
      ,TO_CHAR (contract.fun_getaappdate (a.AAPP_NUM, CONTRACT.FUN_GETCURRNTCONTRACT_YEAR(a.AAPP_NUM), 'E'),'mm/dd/yyyy') AS "END DATE"
      ,CONTRACT.FUN_GETCURRNTCONTRACT_YEAR(a.AAPP_NUM) AS "CONTRACT YEAR"
      ,CONTRACT.FUN_GETESTCOSTPROTOTALAMOUNT(a.AAPP_NUM, 1, CONTRACT.FUN_GETCURRNTCONTRACT_YEAR(a.AAPP_NUM)) AS "ECP Value (CTR-OPS)"
      ,CONTRACT.FUN_GETESTCOSTPROTOTALAMOUNT(a.AAPP_NUM, 6, CONTRACT.FUN_GETCURRNTCONTRACT_YEAR(a.AAPP_NUM)) AS "ECP Value (O/A)"
      ,CONTRACT.FUN_GETESTCOSTPROTOTALAMOUNT(a.AAPP_NUM, 7, CONTRACT.FUN_GETCURRNTCONTRACT_YEAR(a.AAPP_NUM)) AS "ECP Value (CTS)"
FROM AAPP a
    ,LU_FUNDING_OFFICE fo
    ,CENTER c
    ,CONTRACTOR cr

WHERE fo.FUNDING_OFFICE_NUM = a.FUNDING_OFFICE_NUM
  AND c.CENTER_ID(+) = a.CENTER_ID
  AND cr.CONTRACTOR_ID(+) = a.CONTRACTOR_ID
  AND ( 
        (select CONTRACT.FUN_GETCURRNTCONTRACT_YEAR(AAPP_NUM) from dual) != 999
        and
        (select CONTRACT.FUN_GETCURRNTCONTRACT_YEAR(AAPP_NUM) from dual) != 0
      )
  AND AGREEMENT_TYPE_CODE = 'DC' --<--- DOL contracts
;
