
INSERT INTO ORGANIZATIONS (IDS, ABBREVIATION, FULL_NAME)
VALUES (2, 'ECA', 'EDUCATIONAL CULTURAL AFFAIRS');

INSERT INTO ORGANIZATIONS (IDS, ABBREVIATION, FULL_NAME)
VALUES (3, 'IIP', 'OFFICE OF INTERNAL INFORMATION PROGRAMS');

COMMIT;
