CREATE TABLE "Q42ADMIN"."COMMENTS" ("PRJ_ID" NUMBER(10) NOT NULL,
    "USER_ID" NUMBER(10) NOT NULL, "Q_NUM" NUMBER(10) NOT NULL, "COMMENTS" 
    VARCHAR2(4000), PRIMARY KEY("PRJ_ID", "USER_ID", "Q_NUM"))  
    TABLESPACE "USERS"