CREATE OR REPLACE VIEW VIEW_FOR_SP_SELECTUSERSANSWERS AS
SELECT a.PARTICIPANT_ID AS UserID
        ,a.REASERCH_ID AS PrjID
        ,(select Count(*) from ANSWERS aa WHERE a.REASERCH_ID = aa.REASERCH_ID) AS LoopCounter
  FROM ANSWERS a
  ORDER BY 2;

