<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<title>Untitled Document</title>
</head>

<body>
Test<br>

<cfmail server="192.168.10.5"  from="surikovsa@state.gov" to="surikovsa@state.gov;BlockerMD2@state.gov;BowenDC@state.gov" 
subject="Testing e-Mail for Alumni Archive" >

This is a test.
This e-mail is generated by the application Alumni Archive.
Please respond to me if e-mail is received.
Thanks

</cfmail>
<br>
Mail
</body>
</html>

<!--- 
	#pgm_id#
	#pgm_almn_id#
	#pgm_type_cd#
	#pgm_type_nm#
	#pgm_fy_dt#
	#pgm_yr_dt#
						#pgm_start_dt#
						#pgm_end_dt#
	#pgm_from_cntry_cd#
	#pgm_from_cntry_nm#
	#pgm_to_cntry_cd#
	#pgm_to_cntry_nm#
						#pgm_field_stdy_cd# #pgm_field_stdy_nm#
						#pgm_agcy_nm#
						#pgm_plcmnt_org_nm#
						#pgm_nmtng_org_nm#
						#pgm_sub_ctgry_txt#
						#pgm_topic_txt#
						#pgm_strtgc_goal_txt#
						#pgm_spcl_award_txt#
				
						#pgm_updt_dt# 
						#pgm_updt_id#
						#pgm_src_nm#
 --->
