
DROP TABLE COMMENTS CASCADE CONSTRAINTS ; 

CREATE TABLE COMMENTS ( 
  PRJ_ID    NUMBER        NOT NULL, 
  USER_ID   NUMBER        NOT NULL, 
  Q_NUM     NUMBER        NOT NULL, 
  COMMENTS  VARCHAR2 (1), 
  CONSTRAINT PK_COMMENTS
  PRIMARY KEY ( PRJ_ID, USER_ID, Q_NUM ) 
    USING INDEX 
     TABLESPACE USERS PCTFREE 10
     STORAGE ( INITIAL 131072 NEXT 131072 PCTINCREASE 0 ))
   TABLESPACE USERS
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 131072
   NEXT 131072
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS 4096
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 

