
DROP TABLE PROJECT_MANAGERS CASCADE CONSTRAINTS ; 

CREATE TABLE PROJECT_MANAGERS ( 
  PRJ_ID   NUMBER        NOT NULL, 
  USER_ID  NUMBER        NOT NULL, 
  CONSTRAINT PK_PROJECT_MANAGERS
  PRIMARY KEY ( PRJ_ID, USER_ID ) 
    USING INDEX 
     TABLESPACE USERS PCTFREE 10
     STORAGE ( INITIAL 131072 NEXT 131072 PCTINCREASE 0 ))
   TABLESPACE USERS
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 131072
   NEXT 131072
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS 4096
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 

