create sequence ORGANIZATION_ID increment by 1 start with 2;
-------------------------------------------------------------
DROP TABLE ORGANIZATIONS CASCADE CONSTRAINTS ; 

CREATE TABLE ORGANIZATIONS ( 
  IDS           NUMBER (10)   NOT NULL, 
  ABBREVIATION  VARCHAR2 (10)  NOT NULL, 
  FULL_NAME     VARCHAR2 (100)  NOT NULL, 
  CONSTRAINT PK_ORGANIZATION_ID
  PRIMARY KEY ( IDS ) 
    USING INDEX 
     TABLESPACE USERS PCTFREE 10
     STORAGE ( INITIAL 131072 NEXT 131072 PCTINCREASE 0 ))
   TABLESPACE USERS
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 131072
   NEXT 131072
   PCTINCREASE 0
   MINEXTENTS 1
   MAXEXTENTS 4096
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 

ALTER TABLE ORGANIZATIONS ADD 
 UNIQUE (ABBREVIATION)     USING INDEX 
     TABLESPACE USERS PCTFREE 10
     STORAGE ( INITIAL 131072 NEXT 131072 PCTINCREASE 0 ) ;

ALTER TABLE ORGANIZATIONS ADD 
 UNIQUE (FULL_NAME)     USING INDEX 
     TABLESPACE USERS PCTFREE 10
     STORAGE ( INITIAL 131072 NEXT 131072 PCTINCREASE 0 ) ;

---------------------------------------------------------------------------------
CREATE TABLE "Q42ADMIN"."ORGANIZATIONS" 
	(
	 "IDS"          NUMBER(10)    NOT NULL, 
	 "ABBREVIATION" VARCHAR2(10)  NOT NULL, 
	 "FULL_NAME"    VARCHAR2(100) NOT NULL, 
     CONSTRAINT "PK_ORGANIZATION_ID" PRIMARY KEY("IDS"), 
	 UNIQUE("ABBREVIATION"),
     UNIQUE("FULL_NAME")
	) 
     TABLESPACE "USERS" 
	;
	
	
INSERT INTO ORGANIZATIONS (IDS, ABBREVIATION, FULL_NAME)
VALUES (Organization_ID.NextVal, 'ECA', 'EDUCATIONAL CULTURAL AFFAIRS');

INSERT INTO ORGANIZATIONS (IDS, ABBREVIATION, FULL_NAME)
VALUES (Organization_ID.NextVal, 'IIP', 'OFFICE OF INTERNAL INFORMATION PROGRAMS');
