prompt PL/SQL Developer import file
prompt Created on Thursday, April 06, 2006 by ssurikov
set feedback off
set define off
prompt Disabling triggers for TOPIC...
alter table TOPIC disable all triggers;
prompt Truncating TOPIC...
truncate table TOPIC;
prompt Loading TOPIC...
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (2, 202, 'ST', 'Approve Changes in Users', 'Click and find a registered group of users who are requesting your approval of certain changes to their privileges or roles.', 20, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (3, 202, 'ST', 'See Your Active Users', 'Click and find registered and approved users of the Archive at your post (abroad) or in your office (domestic).', 30, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (4, 202, 'ST', 'Pre-Registered Users', 'A group of users whose records were created by the Administrator, but have not yet requested access. Only the Administrator can approve these users.', 40, 'I', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (5, 1001, 'CS', 'Capsule Story 1', 'Lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc., li tot Europa usa li sam vocabularium. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. ', 10, 'I', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (6, 1001, 'CS', 'Who is this site for?', 'This site is for all Department of State staff who are authorized access. Authorization is requested through the registration process.  Staff members stationed abroad must be authorized by the Post''s Public Affairs Officer (PAO) and staff stationed in the United States must be authorized by their Office Director.', 20, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (7, 1001, 'CS', 'Who are ECA Alumni?', 'An alumnus(a) is any person who was selected for and has participated in an educational and cultural affairs funded program.  Once the person has participated in the program he or she becomes an alumnus(a).  ', 30, 'I', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (8, 1001, 'CS', 'Capsule Story 4', 'Del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc., li tot Europa usa li sam vocabularium. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. ', 40, 'I', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (21, 202, 'ST', 'Quick search', 'Application(System) Users could be searched by Last Name, Role, or Country', 40, 'I', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (22, 203, 'ST', 'BASIC SEARCH TIPS', null, 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (23, 203, 'CS', 'First / Last Name', 'Lorem ipsum dolor sit amet, pariatur porta eget, quae sit vivamus condimentum nulla placerat, nulla ac et lorem, nam quis vel wisi molestie pellentesque. Integer libero sit metus adipiscing sed. Dui libero nunc nunc enim mi, est faucibus suscipit. Vivamus suscipit congue, risus risus id porttitor eu. Vel nisl, tellus sed. Malesuada magna at purus maecenas, dis fusce ante quis pretium, blandit vitae at. Orci urna phasellus arcu vel, curae urna enim dignissim elementum, posuere tortor wisi.', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (24, 203, 'CS', 'Program Name', 'Fusce turpis mi purus, vestibulum in est lectus libero urna gravida, odio ante, et venenatis nec sapien wisi. Rutrum aliquam praesent lobortis. Dignissim justo interdum scelerisque pede eget dolor, tempus aenean felis dolor. Justo ac wisi vestibulum, pellentesque consectetuer maecenas consectetuer est ac maecenas, vitae mi lacinia ac, tincidunt eget non, sollicitudin interdum ipsum. Vitae dolor, in in neque posuere libero ultricies maecenas, quisque saepe vitae sagittis morbi mi, congue nulla id orci aenean varius. Pellentesque aliquam, sed hendrerit urna, lacus wisi. ', 20, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (25, 203, 'CS', 'Fiscal Year', 'Quis justo vel at eget lectus, ullamcorper est eleifend ut, et quam a venenatis, totam massa elementum id quisque erat dolor. Justo ipsum orci ac dignissim dolor, at vel adipiscing proin congue, porta accumsan est cras, suscipit id arcu luctus sem, sem aptent. Donec molestie nibh luctus nunc metus, tristique erat etiam, ut pede nullam et et mauris, elit at, neque integer magna sociosqu mauris lacinia praesent. ', 30, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (26, 203, 'CS', 'Program Start Year', 'Dolor curae maecenas. Ut donec sed vel a id nulla. Laoreet wisi fringilla, luctus ut, libero eu vestibulum sem, elementum ultrices in accumsan tincidunt velit.', 40, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (41, 102, 'HT', '101', 'This area of the site will allow you to find Alumni and update / edit the individual Alumni records, in a multitude of ways.', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (42, 103, 'HT', '101', 'Li Europan lingues es membres del sam familie. Europa usa li sam vocabularium. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilit  de un nov lingua franca: on refusa continuar payar custosi traductores. It solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (44, 201, 'HT', '101', 'Lingues es membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc., li tot Europa usa li sam vocabularium. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilit  de un nov lingua franca: on refusa continuar payar custosi traductores. It solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (45, 202, 'HT', '101', 'Membres del sam familie. Lor separat existentie es un myth. Por scientie, musica, sport etc., li tot Europa usa li sam vocabularium. Li lingues differe solmen in li grammatica, li pronunciation e li plu commun vocabules. Omnicos directe al desirabilit  de un nov lingua franca: on refusa continuar payar custosi traductores. It solmen va esser necessi far uniform grammatica, pronunciation e plu sommun paroles.', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (46, 203, 'HT', '101', 'Use the Basic Search to find and edit Alumni by their Name, Country, Years or Program Type.  Here the option to save the searches as a `custom  search` will allow users to return to the same search criteria over and over again!  From here you will get the results of your search in a  summary, and you may select an individual Alumni to edit and update.', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (1, 202, 'ST', 'Approve Users', 'Click and find a group of users who are requesting your approval for access to the Archive.', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (47, 204, 'HT', '101', 'The Advanced search option will allow users to seek out alumni in a very detailed way.  Choosing options where data may be incomplete or vast, the search for alumni may be narrowed down to the individual fields like; Field of Study, Cities Visited, Host institution, and many others.    Here the user may also choose the option to save the searches as a `custom search`.  NOTE: This search area may generate very large lists of alumni, or may narrow the search so significantly that the results may be unknown or zero.  As a precaution, your search will be limited to the return of less than 1000 Alumni at one time. ' || chr(10) || '', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (48, 205, 'HT', '101', 'In the Custom Search area, all the saved searches that have been performed, will be listed so that the user may retrieve them at any time. Custom Searches are named by the user, and stored along with the user`s individual login.  Searches may be `saved` in a variety of formats, based on the needs of the user. Custom Searches are available from anywhere in the system and may be run from any of the screens at any time. ' || chr(10) || '', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (49, 203, 'HT', '102', 'Use the Basic Search to find and edit Alumni by their Name, Country, Years or Program Type.Here the option to save the searches as a `custom  search` will allow users to return to the same search criteria over and over again!  From here you will get the results of your search in a  summary, and you may select an individual Alumni to edit and update.', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (51, 205, 'HT', '102', 'In the Custom Search area, all the saved searches that have been performed, will be listed so that the user may retrieve them at any time. ' || chr(10) || '' || chr(10) || 'Custom Searches are named by the user, and stored along with the user`s individual login.  Searches may be `saved` in a variety of formats, based on the needs of the user. ' || chr(10) || '' || chr(10) || 'Custom Searches are available from anywhere in the system and may be run from any of the screens at any time. ', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (52, 201, 'HT', '104', 'Sic tempus fugit esperanto hiccup estrogen. Glorious baklava ex librus hup hey ad infinitum. Non sequitur condominium facile et geranium incognito. Epsum factorial non deposit quid pro quo hic escorol. Marquee selectus non provisio incongruous feline nolo contendre Olypian quarrels et gorilla congolium sic ad nauseum. Souvlaki ignitus carborundum e pluribus unum.', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (53, 202, 'HT', '104', 'Tempus fugit esperanto hiccup estrogen. Glorious baklava ex librus hup hey ad infinitum. Non sequitur condominium facile et geranium incognito. Epsum factorial non deposit quid pro quo hic escorol. Olypian quarrels et gorilla congolium sic ad nauseum. Souvlaki ignitus carborundum e pluribus unum. Defacto lingo est igpay atinlay. Gratuitous octopus niacin, sodium glutimate.', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (61, 101, 'CS', 'FIND AND UPDATE ALUMNI', 'Go here to look for alumni and update their records.  You will be able to edit their addresses, phone numbers and other contact information.', 102, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (62, 101, 'CS', 'REPORTS AND LISTS', 'This topic is hardcoded', 106, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (63, 101, 'CS', 'ADMIN', 'Go here to update your password, request new privileges or if you are an authorizing agent (PAO or Office Director) <a href="#" onClick="JavaScript: of_CallFile(202)">go here to approve your users</a>.', 104, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (64, 101, 'NW', 'The Roll Out', 'The database currently contains information on 400,000 alumni. By summer 2006 the Washington Alumni Affairs Office will have entered information on 700,000 alumni. So if you don''t find all your alumni right away bear with us - they will soon be here.', 3, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (95, 101, 'NW', 'New Data Added', 'On November 18, 2005 1640 records of Benjamin A. Gilman International Scholarship Program alumni who traveled to 90 countries between Fall 2001 and Spring 2005 were added to the archive.', 1, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (66, 102, 'CS', 'Basic Search', 'Use the Basic Search to find and edit Alumni by their Name, Country, Years or Program Type. Here the option to save the searches as a "custom search" will allow users to return to the same search criteria over and over again!  From here you will get the results of your search in a summary, and you may select an individual Alumni to edit and update. Note: As a precaution, your search will be limited to the return of less than 1000 Alumni at one time to make the results more useable.', 203, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (67, 102, 'CS', 'Advanced Search', 'The Advanced search option will allow users to seek out alumni in a very detailed way.  Choosing options where data may be incomplete or vast, the search for alumni may be narrowed down to the individual fields like; Field of Study, Cities Visited, Host institution, and many others.  Here the user may also choose the option to save the searches as a "custom search". Note:   This search area may generate very large lists of alumni, or may narrow the search so significantly that the results may be zero.  As a precaution, your search will be limited to the return of less than 1000 Alumni at one time.', 204, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (68, 102, 'CS', 'Saved Custom Searches', 'In the Custom Search area, all the saved searches that have been performed will be listed so that the user may retrieve them at any time. Custom Searches are named by the user, and stored along with the user''s individual login.  Searches may be "saved" in a variety of formats, based on the needs of the user. Custom Searches are available from anywhere in the system and may be run from any of the screens at any time.', 205, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (81, 104, 'CS', 'Administer Users', 'This section is for use by users who have the role of PAO, ECA Alumni Coordinator, and the ECA Data Manager. Here you can perform the following:  Approve, Deny or place On-Hold, users who are requesting access to the system.  You can also approve or deny users requests for changes to their privileges or roles.', 202, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (82, 104, 'CS', 'Edit Roles', 'The Edit Roles section is reserved for use by the ECA Data Manager only.  This section identifies the user roles of all enrolled users in the Archive, and for security purposes, is limited in its access.', 201, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (83, 104, 'CS', 'Text Editor', 'The Text Editor section is where News and Announcements may be edited and place for the Home page of the Archive.  Currently only the ECA Data Manager will have access to this section.  (For future use we might want to allow the PAO''s access to this so they can send in NEWS.. or offer that they send, and we post) .?? ', 207, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (85, 104, 'CS', 'Self Data', 'This section is to update your own profile.', 208, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (86, 106, 'CS', 'Create Mailing Labels', 'This is where you can create alumni mailing labels.  Find the alumni, get a list in Excel, decide which data fields you want to include in the mailing labels, then merge them into Word and print mailing labels.' || chr(10) || '', 209, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (87, 106, 'CS', 'Create Contact List', 'This is where you go to create an alumni contact list.  Search for alumni, get a list in Excel, decide which data fields you want include.', 210, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (88, 106, 'CS', 'Create Custom Reports', 'This is where you go to create custom reports.  Select which data fields to include.  Define the search for alumni and run it.  The report will be created in Excel.', 211, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (89, 106, 'CS', 'Chart Report', 'These reports will be available soon. A chart report will show you, in a graphic manner, the statistics on alumni counts and comparisons.', 212, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (90, 106, 'CS', 'Create E-mail Distribution List', 'This is where you go to create an alumni email distribution list. Find the alumni, get a list in Excel, then copy fields into Microsoft Outlook.', 213, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (50, 204, 'HT', '102', 'The Advanced search option will allow users to seek out alumni in a very detailed way.  Choosing options where data may be incomplete or vast, the search for alumni may be narrowed down to the individual fields like; Field of Study, Cities Visited, Host institution, and many others.    Here the user may also choose the option to save the searches as a `custom search`.<br>NOTE: This search area may generate very large lists of alumni, or may narrow the search so significantly that the results may be unknown or zero.  As a precaution, your search will be limited to the return of less than 1000 Alumni at one time. ' || chr(10) || '', 10, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (96, 101, 'NW', '1970', '1970 is our magic year.  Our goal is to collect in this database alumni with programs years since 1970.  You will find some alumni from previous years ¿ if we had their record we kept it.', 4, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (97, 101, 'NW', 'Updating Alumni Contact Information', 'Please update as much contact information as you can. Concentrate on alumni since 1970.  ECA Alumni Affairs has some limited funding to help you do this.  Contact us via email <a href="mailto:AlumniArchive@state.gov">AlumniArchive@state.gov</a> for further information.', 6, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (131, 101, 'NW', '5', '555', 5, 'A', null);
insert into TOPIC (TOPIC_ID, TOPIC_SECURITY_TREE_ID, TOPIC_NAVIGATION_CD, TOPIC_TITLE, TOPIC_TXT, TOPIC_SEQ_ON_PAGE, TOPIC_IS_ACTIVE, TOPIC_EXPRTN_DT)
values (137, 101, 'NW', 'Testing', 'Testing, 1, 2, 3', 2, 'A', null);
commit;
prompt 47 records loaded
prompt Enabling triggers for TOPIC...
alter table TOPIC enable all triggers;
set feedback on
set define on
prompt Done.
