prompt PL/SQL Developer import file
prompt Created on Monday, September 08, 2003 by Sergey Surikov
set feedback off
set define off
prompt Disabling triggers for EXIST_USER_COUNTRY_CITY...
alter table EXIST_USER_COUNTRY_CITY disable all triggers;
prompt Loading EXIST_USER_COUNTRY_CITY...
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Joan E. Hutfles', 'COTE D''IVOIRE', 'ABIDJAN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Papayoro Diop', 'GHANA', 'ACCRA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Brian J. Ahern', 'ETHIOPIA', 'ADDIS ABABA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Wade A. Taylor', 'EGYPT', 'ALEXANDRIA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Brad Duff', 'ALGERIA', 'ALGIERS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('G.Davis', 'KAZAKHSTAN', 'ALMATY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Ernest R. Olivarez', 'JORDAN', 'AMMAN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jon Akin', 'TURKMENISTAN', 'ASHGABAT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Sam Pratt/Roland Neiss', 'ERITREA', 'ASMARA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Thomas Daley', 'PARAGUAY', 'ASUNCION');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Robert Burkhart', 'GREECE', 'ATHENS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jonathan Kirkpatrick', 'AZERBAIJAN', 'BAKU');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Ken Zincke', 'MALI', 'BAMAKO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('David Yeutter', 'THAILAND', 'BANGKOK');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Frontis Wiggins', 'CHINA', 'BEIJING');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Frontis Wiggins', 'CHINA', 'BEIJING');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Bruce R. Chaplin', 'LEBANON', 'BEIRUT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('W.Gilsdorf', 'SERBIA AND MONTENEGRO', 'BELGRADE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Joyce Clark', 'BELIZE', 'BELIZE CITY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Anthony Muse', 'GERMANY', 'BERLIN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Anthony Muse', 'GERMANY', 'BERLIN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Anthony Muse', 'GERMANY', 'BERLIN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Simon M Guerrero', 'COLOMBIA', 'BOGOTA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Howard L.  Keegan', 'BRAZIL', 'BRASILIA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Marcia W. Dougherty', 'SLOVAKIA', 'BRATISLAVA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Charles O''Malley', 'BARBADOS', 'BRIDGETOWN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Woody Franke', 'BELGIUM', 'BRUSSELS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Ronnie Fontenot', 'ARGENTINA', 'BUENOS AIRES');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Donald Snead', 'BURUNDI', 'BUJUMBURA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Wade A. Taylor', 'EGYPT', 'CAIRO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('William L. Smith', 'INDIA', 'CALCUTTA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Bev Matte', 'CANADA', 'CALGARY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Roger Cohen', 'AUSTRALIA', 'CANBERRA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John C. Adams', 'SOUTH AFRICA', 'CAPE TOWN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Naseem Loane', 'MOROCCO', 'CASABLANCA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Steve Schuman', 'CHINA', 'CHENGDU');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('James Foster', 'INDIA', 'CHENNAI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Samuel Berardif', 'MOLDOVA', 'CHISINAU');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Hershel Jackson', 'MEXICO', 'CIUDAD JUAREZ');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('B.R. Begnell', 'SRI LANKA', 'COLOMBO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Dwayne Taylor', 'GUINEA', 'CONAKRY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Dustin Lumley', 'DENMARK', 'COPENHAGEN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Michael Lawrence', 'BENIN', 'COTONOU');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('David Fleming', 'SENEGAL', 'DAKAR');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Don ljames', 'TANZANIA', 'DAR ES SALAAM');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mohammad A. Chaudhry', 'BANGLADESH', 'DHAKA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Barbara Sultan', 'DJIBOUTI', 'DJIBOUTI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Frederick E. Ogg', 'QATAR', 'DOHA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Vella Mbenna', 'SIERRA LEONE', 'FREETOWN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Marvin L. Adams', 'BOTSWANA', 'GABORONE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Peter Jenson', 'SWITZERLAND', 'GENEVA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('James Whalen', 'MEXICO', 'GUADALAJARA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jeff Schroeder', 'CHINA', 'GUANGZHOU');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Michael J. Rinker', 'GUATEMALA', 'GUATEMALA CITY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Edwin V. Siasici', 'ECUADOR', 'GUAYAQUIL');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Anthony Muse', 'GERMANY', 'HAMBURG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Aziz Ahmed', 'ZIMBABWE', 'HARARE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Marc Beroud', 'CUBA', 'HAVANA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Marcia K. Henke', 'FINLAND', 'HELSINKI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Brian Bennett', 'VIETNAM', 'HO CHI MINH CITY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('James Maddox', 'CHINA', 'HONG KONG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mel Rollins', 'PAKISTAN', 'ISLAMABAD');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Joseph Cole', 'TURKEY', 'ISTANBUL');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Barry Peterson', 'INDONESIA', 'JAKARTA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Michael McCowan', 'SOUTH AFRICA', 'JOHANNESBURG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Kevin Inglis', 'UGANDA', 'KAMPALA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Tom Barnes', 'UKRAINE', 'KIEV');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Gerald W. Bochart', 'RWANDA', 'KIGALI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John Benton', 'JAMAICA', 'KINGSTON');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Floyd Wilson', 'CONGO', 'KINSHASA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jack Anderson', 'POLAND', 'KRAKOW');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Meredith Donaway', 'MALAYSIA', 'KUALA LUMPUR');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Timothy S. Williams', 'KUWAIT', 'KUWAIT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Greg Tyson', 'BOLIVIA', 'LA PAZ');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Anthony Muse', 'GERMANY', 'LEIPZIG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jim Fox', 'GABON', 'LIBREVILLE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('E. Alex Cooper', 'MALAWI', 'LILONGWE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Fred Armand', 'PERU', 'LIMA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Maurice C. Crossland', 'PORTUGAL', 'LISBON');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Barry W. Rice', 'ZAMBIA', 'LUSAKA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Raymond Harger', 'LUXEMBOURG', 'LUXEMBOURG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Robert Klinger', 'NICARAGUA', 'MANAGUA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Matthew McClammy', 'BAHRAIN', 'MANAMA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Richard J. Herkert', 'PHILIPPINES', 'MANILA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Richard Gunn', 'FRANCE', 'MARSEILLE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('IM FSN-E.Marquez', 'MEXICO', 'MATAMOROS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Bruce MacEwen', 'SWAZILAND', 'MBABANE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mike Kovich', 'MEXICO', 'MEXICO CITY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mike Kovich', 'MEXICO', 'MEXICO CITY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mark Nichols', 'ITALY', 'MILAN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Harry Chamberlain', 'BELARUS', 'MINSK');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mark Hodgson', 'URUGUAY', 'MONTEVIDEO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jeffrey Flynn', 'CANADA', 'MONTREAL');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mark Brewer', 'INDIA', 'MUMBAI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Scott D. Ternus', 'GERMANY', 'MUNICH');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jim Davidson', 'OMAN', 'MUSCAT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jim Vanderpool', 'KENYA', 'NAIROBI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Terry Mays', 'ITALY', 'NAPLES');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Dennis Thatcher', 'INDIA', 'NEW DELHI');
commit;
prompt 100 records committed...
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Robert McCumber', 'CYPRUS', 'NICOSIA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Rydell Fletcher', 'MAURITANIA', 'NOUAKCHOTT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Peter Steitz', 'JAPAN', 'OSAKA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('David Gilmore', 'NORWAY', 'OSLO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Edmund J. Gagliardi', 'CANADA', 'OTTAWA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Josetito Nakpil', 'BURKINA FASO', 'OUAGADOUGOU');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Terry Mays', 'ITALY', 'PALERMO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Robert J. Knott', 'PANAMA', 'PANAMA CITY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Eley M. Johnson', 'SURINAME', 'PARAMARIBO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Richard Gunn', 'FRANCE', 'PARIS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Ron Rooker', 'CAMBODIA', 'PHNOM PENH');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Lizzie Slater', 'MAURITIUS', 'PORT LOUIS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Robert Arriaga', 'HAITI', 'PORT-AU-PRINCE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('David Rowles', 'CZECH REPUBLIC', 'PRAGUE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('David P. Jesser', 'SOUTH AFRICA', 'PRETORIA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Faye McClendon', 'SERBIA AND MONTENEGRO', 'PRISTINA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Christopher Gustavus', 'ECUADOR', 'QUITO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Kevin N. Bradshaw', 'MOROCCO', 'RABAT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Michael E. Yoho', 'BURMA', 'RANGOON');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Walter Yates', 'ICELAND', 'REYKJAVIK');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Paul wright', 'LATVIA', 'RIGA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('T. Rebarick', 'BRAZIL', 'RIO DE JANEIRO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Leo Bourne', 'SAUDI ARABIA', 'RIYADH');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John P. Boulanger', 'ITALY', 'ROME');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jose M. Ortiz', 'COSTA RICA', 'SAN JOSE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Charles E. Fleenor', 'EL SALVADOR', 'SAN SALVADOR');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Diane Stuart', 'YEMEN', 'SANAA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Brian Powers', 'CHILE', 'SANTIAGO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Art Mendez', 'BRAZIL', 'SAO PAULO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Michael F. Ingram', 'BOSNIA AND HERZEGOVINA', 'SARAJEVO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Karen Finer', 'CHINA', 'SHANGHAI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jerry Shepard', 'CHINA', 'SHENYANG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Robert S. Blankenship', 'SINGAPORE', 'SINGAPORE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Ray Shankweiler', 'MACEDONIA', 'SKOPJE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Dane Howard', 'BULGARIA', 'SOFIA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Russell G. LeClair Jr.', 'SWEDEN', 'STOCKHOLM');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Richard Gunn', 'FRANCE', 'STRASBOURG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Gary Harral', 'UZBEKISTAN', 'TASHKENT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Bob Lynn', 'GEORGIA', 'TBILISI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Tim Cook', 'HONDURAS', 'TEGUCIGALPA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mari Jain Womack', 'NETHERLANDS', 'THE HAGUE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Carlos Acosta', 'MEXICO', 'TIJUANA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John Kane', 'ALBANIA', 'TIRANA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Julius Benyik', 'CANADA', 'TORONTO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Ross Campbell', 'TUNISIA', 'TUNIS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Kenneth Hoeft', 'BELGIUM', 'USNATO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('J. Kelley Razer', 'MALTA', 'VALLETTA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Cindy Bonderoff', 'CANADA', 'VANCOUVER');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('David frazee', 'LAOS', 'VIENTIANE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Dennis Severns', 'LITHUANIA', 'VILNIUS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Clifford Brzozowski', 'POLAND', 'WARSAW');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Steve Derrick', 'NEW ZEALAND', 'WELLINGTON');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Leslie D. Oly', 'CAMEROON', 'YAOUNDE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Cal McQueen', 'ARMENIA', 'YEREVAN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Ted Cross', 'CROATIA', 'ZAGREB');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Ergibe Boyd', 'COTE D''IVOIRE', 'ABIDJAN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('David Queen', 'GHANA', 'ACCRA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jeremy Carper', 'ETHIOPIA', 'ADDIS ABABA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('James L. Bullock', 'EGYPT', 'ALEXANDRIA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Maya Harris', 'ALGERIA', 'ALGIERS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('J.Kenney', 'KAZAKHSTAN', 'ALMATY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Haynes Mahoney', 'JORDAN', 'AMMAN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Shannon Runyon', 'TURKMENISTAN', 'ASHGABAT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Ilya Levine', 'ERITREA', 'ASMARA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Karen Williams', 'PARAGUAY', 'ASUNCION');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Sandra Kaiser', 'GREECE', 'ATHENS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Theresa Markiw', 'AZERBAIJAN', 'BAKU');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Daniel Hamilton', 'MALI', 'BAMAKO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mark Larsen', 'THAILAND', 'BANGKOK');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Donald Bishop', 'CHINA', 'BEIJING');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Donald Bishop', 'CHINA', 'BEIJING');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Candace Putnam', 'LEBANON', 'BEIRUT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Allen Docal', 'SERBIA AND MONTENEGRO', 'BELGRADE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Edward Keeton', 'GERMANY', 'BERLIN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Richard Schmierer', 'GERMANY', 'BERLIN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Richard Schmerer', 'GERMANY', 'BERLIN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('James Frost', 'COLOMBIA', 'BOGOTA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Patrick J. Linehan', 'BRAZIL', 'BRASILIA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Barbara Zigli', 'SLOVAKIA', 'BRATISLAVA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Kathleen Boyle', 'BARBADOS', 'BRIDGETOWN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Carolyn Johnson', 'BELGIUM', 'BRUSSELS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Anne Barbaro', 'BELGIUM', 'BRUSSELS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mark Krischik', 'ARGENTINA', 'BUENOS AIRES');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John Marietti', 'BURUNDI', 'BUJUMBURA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('James L. Bullock', 'EGYPT', 'CAIRO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Rex Moser', 'INDIA', 'CALCUTTA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Betty Rice', 'CANADA', 'CALGARY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Susan Crystal', 'AUSTRALIA', 'CANBERRA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Lou Mazel', 'SOUTH AFRICA', 'CAPE TOWN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Amy Tachco', 'MOROCCO', 'CASABLANCA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John Louton', 'CHINA', 'CHENGDU');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Helen Lafave', 'INDIA', 'CHENNAI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Aleisha Woodward', 'MOLDOVA', 'CHISINAU');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Vacant', 'MEXICO', 'CIUDAD JUAREZ');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('B.A. Lohof', 'SRI LANKA', 'COLOMBO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Chris Fitzgerald', 'DENMARK', 'COPENHAGEN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jennifer Schaming', 'BENIN', 'COTONOU');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Michael Pelletier', 'SENEGAL', 'DAKAR');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mike Korff', 'TANZANIA', 'DAR ES SALAAM');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Karl Fritz', 'BANGLADESH', 'DHAKA');
commit;
prompt 200 records committed...
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Chase Beamer', 'DJIBOUTI', 'DJIBOUTI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Patricia Kabra', 'QATAR', 'DOHA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Kevin Green', 'SIERRA LEONE', 'FREETOWN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Karen M. Morrisey', 'BOTSWANA', 'GABORONE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John D. Hamill', 'SWITZERLAND', 'GENEVA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Angela Emerson', 'MEXICO', 'GUADALAJARA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Wendy Lyle', 'CHINA', 'GUANGZHOU');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mary Thompson-Jones', 'GUATEMALA', 'GUATEMALA CITY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Ana Theresa Nouhra', 'ECUADOR', 'GUAYAQUIL');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('William Cook', 'GERMANY', 'HAMBURG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Lucy Hall', 'ZIMBABWE', 'HARARE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Kelly Keiderling', 'CUBA', 'HAVANA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Victoria Middleton', 'FINLAND', 'HELSINKI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Robert Ogborn', 'VIETNAM', 'HO CHI MINH CITY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Richard Stites', 'CHINA', 'HONG KONG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Andrew Steinfeld', 'PAKISTAN', 'ISLAMABAD');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Walter Douglas', 'TURKEY', 'ISTANBUL');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Charles Silver', 'INDONESIA', 'JAKARTA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Julius Chamane', 'SOUTH AFRICA', 'JOHANNESBURG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Michael C. Gonzales', 'UGANDA', 'KAMPALA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Janet Demiray', 'UKRAINE', 'KIEV');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Eric Wong', 'RWANDA', 'KIGALI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Orna Blum', 'JAMAICA', 'KINGSTON');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Victoria Delong', 'CONGO', 'KINSHASA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('William Bellis', 'POLAND', 'KRAKOW');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Karl Stoltz', 'MALAYSIA', 'KUALA LUMPUR');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John G. Moran', 'KUWAIT', 'KUWAIT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Thomas Genton', 'BOLIVIA', 'LA PAZ');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Elizabeth Bonkowsky', 'GERMANY', 'LEIPZIG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Moulik Berkana', 'GABON', 'LIBREVILLE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Robin R. Diallo', 'MALAWI', 'LILONGWE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Josie Shumake', 'PERU', 'LIMA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Joao Ecsodi', 'PORTUGAL', 'LISBON');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('James F. Greene', 'ZAMBIA', 'LUSAKA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jan Hartman', 'NICARAGUA', 'MANAGUA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Aleta Wanger', 'BAHRAIN', 'MANAMA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Ronald J. Post', 'PHILIPPINES', 'MANILA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Renee Earle', 'FRANCE', 'MARSEILLE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('RCO-J.Alejandro', 'MEXICO', 'MATAMOROS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Roger Kenna', 'SWAZILAND', 'MBABANE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jeff Brown', 'MEXICO', 'MEXICO CITY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jeff Brown', 'MEXICO', 'MEXICO CITY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Thomas Skipper', 'ITALY', 'MILAN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Dian McDonald', 'BELARUS', 'MINSK');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Melissa Martinez', 'URUGUAY', 'MONTEVIDEO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Alyson Gunder', 'CANADA', 'MONTREAL');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Anne Grimes', 'INDIA', 'MUMBAI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Robert Hugins', 'GERMANY', 'MUNICH');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Tanya Anderson', 'OMAN', 'MUSCAT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Peter Claussen', 'KENYA', 'NAIROBI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Gloria F. Berbena', 'ITALY', 'NAPLES');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Michael Anderson', 'INDIA', 'NEW DELHI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Craig Kuehl', 'CYPRUS', 'NICOSIA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Babaly A. Sy', 'MAURITANIA', 'NOUAKCHOTT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Chris Laycock', 'JAPAN', 'OSAKA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Oscar Trevino', 'NORWAY', 'OSLO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('James H. Williams', 'CANADA', 'OTTAWA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Richard Nikyema', 'BURKINA FASO', 'OUAGADOUGOU');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Gloria Berbena', 'ITALY', 'PALERMO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Eugene Santoro', 'PANAMA', 'PANAMA CITY');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Vernelle Trim', 'SURINAME', 'PARAMARIBO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Renee Earle', 'FRANCE', 'PARIS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Heide Bronke', 'CAMBODIA', 'PHNOM PENH');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Vacant', 'MAURITIUS', 'PORT LOUIS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John Trunzo', 'HAITI', 'PORT-AU-PRINCE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Evelyn A. Early', 'CZECH REPUBLIC', 'PRAGUE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Virginia Farris', 'SOUTH AFRICA', 'PRETORIA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Michael McClellan', 'SERBIA AND MONTENEGRO', 'PRISTINA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Marti Estell', 'ECUADOR', 'QUITO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Anne O''Leary', 'MOROCCO', 'RABAT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Mary E. Countryman', 'BURMA', 'RANGOON');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Linda Hartley', 'ICELAND', 'REYKJAVIK');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Victoria Sloan', 'LATVIA', 'RIGA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('C. Jarvis', 'BRAZIL', 'RIO DE JANEIRO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John Burgess', 'SAUDI ARABIA', 'RIYADH');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John P. Dwyer', 'ITALY', 'ROME');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Peter Brennan', 'COSTA RICA', 'SAN JOSE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Lane Cubstedd', 'EL SALVADOR', 'SAN SALVADOR');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John Bailian', 'YEMEN', 'SANAA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Julie G. Connor', 'CHILE', 'SANTIAGO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Vivian Keller', 'BRAZIL', 'SAO PAULO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Douglas L. Ebner', 'BOSNIA AND HERZEGOVINA', 'SARAJEVO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jennifer Galt', 'CHINA', 'SHANGHAI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Cynthia Caples', 'CHINA', 'SHENYANG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('David R. Andersen', 'SINGAPORE', 'SINGAPORE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Deborah jones', 'MACEDONIA', 'SKOPJE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('John Johnson', 'BULGARIA', 'SOFIA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Gregory Elfman', 'SWEDEN', 'STOCKHOLM');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Renee Earle', 'FRANCE', 'STRASBOURG');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('David M. Reinert', 'UZBEKISTAN', 'TASHKENT');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Sharon Hudson-Dean', 'GEORGIA', 'TBILISI');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Melissa Cooper', 'HONDURAS', 'TEGUCIGALPA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jess Baily', 'NETHERLANDS', 'THE HAGUE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jose Ramon Banuelos', 'MEXICO', 'TIJUANA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Gregory Kay', 'ALBANIA', 'TIRANA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Phill Hoffman', 'CANADA', 'TORONTO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Philip Breeden', 'TUNISIA', 'TUNIS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Barry Levin', 'BELGIUM', 'USNATO');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Erik Holm-Olsen', 'MALTA', 'VALLETTA');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Rosemary Eng', 'CANADA', 'VANCOUVER');
commit;
prompt 300 records committed...
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('James Warren', 'LAOS', 'VIENTIANE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Anthony Pahigian', 'LITHUANIA', 'VILNIUS');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Andrew Koss', 'POLAND', 'WARSAW');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('William Millman', 'NEW ZEALAND', 'WELLINGTON');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Jose Santacana', 'CAMEROON', 'YAOUNDE');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Kimberly Hargan', 'ARMENIA', 'YEREVAN');
insert into EXIST_USER_COUNTRY_CITY (EUCC_U_FULLNAME, EUCC_COUNTRY, EIUCC_CITY)
values ('Janet Edmonson', 'CROATIA', 'ZAGREB');
commit;
prompt 306 records loaded
prompt Enabling triggers for EXIST_USER_COUNTRY_CITY...
alter table EXIST_USER_COUNTRY_CITY enable all triggers;
set feedback on
set define on
prompt Done.
